### ISSUE TITLE
LAN traffic not blocked

### ISSUE THREAD

**Issue by YZgitter** [tnodir/fort#132]
I have filter mode set to "Block, if not allowed".
All the programs and services are set to "Block" and I also unchecked "Restrict access to LAN only" for all of them.

And yet I'm able to ping another computer on the local network. (The only way to prevent that is if I add the LAN IP ranges to the included "Internet Addresses", but I don't think that's how it's supposed to work.)

Is that a bug?

**Comment by Emi-Emi-Emi** [comment]
You need to enable `Filter Local Addresses' in Options.

**Comment by YZgitter** [comment]
I enabled that too and it's still not blocked. I can still ping the other PC.

And I thought that filter was for loopback stuff, for programs like Firefox.
But, even with that enabled, Fort didn't detect Firefox. Another firewall always detects it making a connection to 127.0.0.1.

**Comment by Emi-Emi-Emi** [comment]
Oh yeah oops, now I remember.
You have to remove the connections from Options -> IP addresses (Internet Addresses) and remove the IP you don't want your PC to use.

IP address = apply to all programs and at the moment Fort works as everything is for inbound and outbound though, you will block both ways BTW.

Also to stop stop the pinging in the other computer, you must block `System` or `NT Kernel & System` in the remote device, if not you also will block the pinging to remote devices, unless you allow the IP of the remote devices in the IP addresses (Internet Addresses).

Also, `Restrict access to LAN only`, does exactly that, restrict programs to only use LAN, so the option would have never stopped the ping BTW.

**Comment by YZgitter** [comment]
> You have to remove the connections from Options -> IP addresses (Internet Addresses) and remove the IP you don't want your PC to use.

Yes, I can see that.
But doing that affects all programs, so the _per-program_ setting "Restrict access to LAN only" doesn't make any sense, because it has no effect.
If that's the only way it works, it's a bug or a missing feature.

**Comment by Emi-Emi-Emi** [comment]
Yes, it affects all programs, that's why you have to remove (I guess) `192.168.0.0/16` and then block `NT Kernel & System`, allowing a program will allow all IPs, the IP addresses Internet Addresses technically only work if a program is blocked.

So for example, if you want to ping to your router and your router is 192.168.0.1, then you can add it that IP and it will ping, or you allow the System and done.

If you wonder what the `Allowed Internet Address` is for, well, if you add 18.0.0.0/8 to the exclude list and go to search.brave.com, only the document will be downloaded by no other resource (unless you already visited the page and it is in the cache, which you should refresh bypassing cache or reload and clear cache for it to work properly)

But yes, it applies to all programs, that's why this issue was made https://github.com/tnodir/fort/issues/2 to allow to tweak rules for individual programs, and including ports and IPs and if it is inbound or outbound and all that. Since Fort doesn't do ports yet either, which is also important for some stuff as well.

And well, `Restrict access to LAN only` matters if a Program needs only LAN and that's it, since allowing a program = all IPs, that means it will not let anything but LAN, so it can be useful in some situations but rarely.

**Comment by tnodir** [comment]
1. Please see the ["Filtering steps"](https://github.com/tnodir/fort/wiki/FAQ#filtering-steps).
2. And what is the ["Internet Addresses" tab](https://github.com/tnodir/fort/wiki/FAQ#what-is-the-difference-between-internet-addresses-and-allowed-internet-addresses-on-the-ip-addresses-tab).

**Comment by YZgitter** [comment]
> `Internet Addresses` = applies to blocked/not allowed programs. `Allowed Internet Addresses` = applies to Allowed programs.
> 
I don't think this is very accurate, because even if both "Internet Addresses" and "Allowed Internet Addresses" include a LAN range and a program is set to _Allow_ with "LAN only", the program will be blocked completely.


Just to be clear, a simple question: Is it possible in Fort to block one program completely, from LAN too, while allowing another program to LAN only?

That's what I expect when I see that one program is "blocked" and the other is set to "LAN only".

But if this is not possible, the UI should change, because currently it's giving misleading information and may lead to security problems.

**Comment by tnodir** [comment]
@YZgitter The "LAN"'s addresses depends on global "Internet Addresses" option.

So< I'll rename the program's "Restrict access to LAN only" flag to "Block Internet traffic".

**Comment by YZgitter** [comment]
> So, I'll rename the program's "Restrict access to LAN only" flag to "Block Internet traffic".

Yes, I think that's better, because it's more accurate.
Also, if that setting doesn't do anything when the program is set to "Block" (that's how it works, right?), the checkbox should only be available when it's set to "Allow". So it might be better to move it to a different position as well, under the Allow/Block buttons.

**Comment by tnodir** [comment]
> Also, if that setting doesn't do anything when the program is set to "Block" (that's how it works, right?), the checkbox should only be available when it's set to "Allow". So it might be better to move it to a different position as well, under the Allow/Block buttons.

Yes, that makes sense. Thanks.

**Comment by tnodir** [comment]
Fixed by 59bd6992.

**Comment by tnodir** [comment]
Fixed in [v3.10.2](https://github.com/tnodir/fort/releases/tag/v3.10.2).
