### ISSUE TITLE
windows explorer - file explorer (win 10+)

### ISSUE THREAD

**Issue by b-user** [tnodir/fort#176]
Windows Explorer has a new name - It's called File Explorer in Windows 10
https://support.microsoft.com/en-us/windows/windows-explorer-has-a-new-name-c95f0e92-b1aa-76da-b994-36a7c7c413d7

![windows explorer - file explorer](https://github.com/tnodir/fort/assets/11581901/1b5ccc8e-296c-486b-b9c5-b7d89302f02b)

When migrating to Windows 10+, it's probably worth changing the wording in the interface.

**Comment by Emi-Emi-Emi** [comment]
I think the problem with this is that the 'context menu' is not talking about File Explorer, but about the Shell `explorer.exe` process, which is still called Windows Explorer, not the file manager.

Winrar calls it "shell integration' 

### Windows Task manager:
![image](https://github.com/tnodir/fort/assets/152097351/ccc781b6-f101-4718-b10f-4a3a51c76d41)
### System Informer:
![image](https://github.com/tnodir/fort/assets/152097351/3c50a5c2-5022-42e1-8bf9-1e25ef660917)


In any case, the wording I think should be "Windows context menu integration"

Also, for Win11, it would be nice if it was also integrated in the new Context Menu

Which can easily be done by using the exact registry values Fort already uses but changing from `Shell\Fort Firewall` to `Shell\SetDesktopWallpaper`

This is how Peazip did it. https://github.com/peazip/PeaZip/tree/sources/peazip-sources/res/share/batch/Windows/Windows%2011%20mini%20context%20menu

![image](https://github.com/tnodir/fort/assets/152097351/ffa70cbe-f8b6-41f1-bc5b-b3fda2dda9e3)

Of course by using SetDesktopWallpaper is the easy hacky way. But for example other menu items can be used as well, like `pintohome` and all that, the only difference is positioning in the menu and the icon it will use since it will just use the icon already made for those elements as shown in screenshot, or like for example, if `pintostartscreen` is used, it will replace the current `Pin To Start` when you right click an exe. This means wallpaper one is a good one for exe because you know there won't be a setdesktopwallpaper for an exe.

Seems like the only way to properly add this is with Windows complicated stuff, so it seems more complicated than what it needs to be for these kind of stuff.

https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

>Apps extend the menu with IExplorerCommand + app identity. Unpackaged Win32 apps can use [Sparse Manifests](https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages). IExplorerCommand support extends back to Windows 7.

BTW, since we have Wildcard in Programs, wouldn't be good if Fort Firewall also had the context menu for folders, and just open/added the directory path in the Edit Wildcard?

If optional/user choice is wanted, then there can be a `Shell integration` (as winrar does) section in Options and then two checkbox one to add context menu for executables and another for folders.

**Comment by Emi-Emi-Emi** [comment]
Yeah, it is still a Shell integration, that's what I said and you are pretty much agreeing with me, So I don't get the issue here, it is pretty common to call it so, winrar, xyplorer do it, because context menus are part of the shell.

The registry key for context menus is "shell" for the new and the legacy menu, and the reason why you are getting the same (legacy) Windows context menu's in File Picker/Dialogs as you do in other File Managers like Far or XYplorer or Xplorer2 and so on, which you are even showing screenshots of it.

You are the one who said `File Explorer` is the new name, and therefore `Windows Explorer integration` is not the right name to use for Win11, and (I guess) that it should be changed to _File Explorer integration_.

But when I talked about `explorer.exe` I didn't say explorer.exe is the only thing on Windows for the shell or UI, because I know explorer.exe can be terminated or replaced, and it can still function by the basic UI, like how you can get the 'new' file picker with libraries, home and all features and dark mode, and works and looks as the File Explorer, but doesn't depend or requires explorer.exe to work.
Even Widows Recovery Environment / Windows installation, has the basic UI with nice file dialog, and nice icons and context menus and all, and I am sure it could be 'hacked' just the same because regedit exists there.

So that's why I was still saying how calling it "Windows explorer integration" is fine, at least it is understood what it might mean, since the explorer.exe is still called **Windows Explorer**, and only the part of the **file manager** is the one called **File Explorer**.

I also went ahead and suggested the **_correct_** term, which would be "Windows context menu", because you still get features and menus without Windows Explorer =  explorer.exe, so Windows Explorer Integration can mean a lot of things anyway.

This is why if you terminate explorer.exe and then use a Program Launcher like Flow Launcher or PowerToys Run, and open `File Explorer`, that won't restore the taskbar or start menu or modern alt+tab or anything 'modern',  still, the file explorer can open as if it was any other 3p file manager by starting as `/factory,{00000000-0000-0000-0000-000000000000} -Embedding` .
So 'File Explorer' is part of explorer.exe just as 'Desktop' is as well, and because you get the new Win11 context menu in both places, makes it clear they are a _Windows Explorer_ feature and `explorer.exe` was programmed to render when reading registry keys, and this is why just changing `Fort Firewall` registry key to `SetDesktopWallpaper` immediately places Fort Firewall in both context menus, without any questions.

Anyway, this is the long explanation what I mean in the first paragraph of my comment. 👍
