### ISSUE TITLE
Password request on uninstall

### ISSUE THREAD

**Issue by tnodir** [tnodir/fort#51]
[ Request ] password function need more protection, when I uninstall FF it requires exit from tray icon and FF won't exit without password and that's fine, but I still can kill FF from task manager and uninstall FF normally, So we need password request when try to uninstall it.

(Extracted from #46)

**Comment by tnodir** [comment]
I'll remove password protection from Fort's UI Quit button.

Rationale:
- Any user should easily run and close the UI part.
- If you need protection, then run Fort as Service and set Password. So, only Admin can stop the Service and only Users, who know the Password, can change Fort's options from UI part.

**Comment by anwar-alsilwy** [comment]
Most of computers have administration user, we need to protect FF from being uninstalled, and against any changes on the UI,
I don't care about stopping service, because I enabled 'Stop traffic while FF is closed'
There is an app called Tinywall:
https://tinywall.pados.hu/
It has a password feature, and you cannot uninstall Tinywall without input password, please check it out.

**Comment by anwar-alsilwy** [comment]
Ok, I see
So, No protection is perfect !!
The most important thing is we need to prevent anyone to completely uninstall FF, it doesn't matter if the FF UI closed or service stop, we can enable "Stop traffic if FF closed" this is great feature by the way.

So, how about place password hash file deeply inside "system32" folder and make FF reading this file before uninstall process and requesting to enter password !!?

I know that professional people can detect that file by reading source information, but most people didn't have that kind of experience.

**Comment by tnodir** [comment]
Ok, let me see what I can do...

**Comment by tnodir** [comment]
Implemented in [v3.7.7](https://github.com/tnodir/fort/releases/tag/v3.7.7).

**Comment by anwar-alsilwy** [comment]
Testing....

**Comment by anwar-alsilwy** [comment]
Ok, I tested v3.7.8
Great thanks for implemented password protection while uninstall, it's working as expected.
But still one thing, on fortfirewall.ini file, I can simply delete "passwordhash=xxxxxxx" or add (#) before line, to bypass protection.
I noticed that even if I delete "passwordhash=xxxxxxx" the protection password of Uninstall still exist, that's interesting 🤔, Maybe uninstall.exe read password info from different place.
So, how about making FF UI & Uninstall.exe read password from same hidden place, because fortfirewall.ini is too obvious and we can bypass protection easily.

Great thanks again 😊

**Comment by tnodir** [comment]
Actually it’s not hidden, but just registry key “HKLM/SOFTWARE/Fort Firewall/passwordHash”.

Yes, we can migrate the key from .ini to registry.

**Comment by anwar-alsilwy** [comment]
> * you must have admin rights to write in registry

I think we must have admin rights to install FF Service mode and driver, so it doesn't matter in password case.



> * FFw supports portable installation and password should be saved in .ini

Yes you right,  but it will be a big vulnerability for wonderful project like Fort Firewall, if the FF installed into pc, so password must be migrate to registry or somewhere else, in portable mode we can keep it in .ini file.

**Comment by tnodir** [comment]
> it will be a big vulnerability

1. We are talking about non-professional user with admin rights;
2. If you can reproduce the vulnerability only with admin rights, then it's not a vulnerability.

Sorry, I don't want spend more time on this feature.
There are other important features for now.

**Comment by anwar-alsilwy** [comment]
On my country, all internet cafe shops run with admin rights for all PCs, we won't limit or block some applications and we don't want any customer to disable/allow/or uninstall FF himself.
That's why I like password feature.

Anyway, my apologies, I don't want to waste your time,  you did your best.

Cheers bro.

**Comment by tnodir** [comment]
> internet cafe shops run with admin rights for all PCs

Oh, that's other story then.
Lets leave this task open and use the feature as is. Maybe we'll improve it later.

**Comment by tnodir** [comment]
> how about making FF UI & Uninstall.exe read password from same hidden place

Implemented in [v3.8.3](https://github.com/tnodir/fort/releases/tag/v3.8.3).
